image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: build
        services:
          - docker
        script:
          - docker run -v `pwd`:/data danielfett/markdown2rfc FAPI_2_0_Baseline_Profile.md
          - mv fapi-2_0-baseline-01.html fapi-2_0-baseline.html
        artifacts:
          - fapi-2_0-baseline.html
  branches:
    master:
      - step:
          name: build
          services:
            - docker
          script:
            - docker run -v `pwd`:/data danielfett/markdown2rfc FAPI_2_0_Baseline_Profile.md
            - mv fapi-2_0-baseline-01.html fapi-2_0-baseline.html
          artifacts:
            - fapi-2_0-baseline.html
      - step:
          name: publish
          clone:
            enabled: false
          script:
            - git config --global user.email "pipeline@bitbucket.org"
            - git config --global user.name "Bitbucket FAPI Pipeline"
            - git config --global push.default simple
            - git clone git@bitbucket.org:openid/openid.bitbucket.io.git
            - mkdir -p openid.bitbucket.io/fapi/
            - cp fapi-2_0-baseline.html openid.bitbucket.io/fapi/
            - cd openid.bitbucket.io/fapi
            - git add *
            - git commit -m "Automatic update of FAPI drafts by pipeline"
            - git push origin master
