image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: build
        services:
          - docker
        script:
          - wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-linux-amd64.tar.gz
          - tar -xzvf pandoc-3.1.9-linux-amd64.tar.gz pandoc-3.1.9/bin/pandoc
          - ./build-all.py
        artifacts:
          - '*.html'
          - '*.xml'
  branches:
    master:
      - step:
          name: build
          services:
            - docker
          script:
            - wget https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-linux-amd64.tar.gz
            - tar -xzvf pandoc-3.1.9-linux-amd64.tar.gz pandoc-3.1.9/bin/pandoc
            - ./build-all.py
          artifacts:
            - '*.html'
            - '*.xml'
      - step:
          name: publish
          clone:
            enabled: false
          script:
            - git config --global user.email "pipeline@bitbucket.org"
            - git config --global user.name "Bitbucket FAPI Pipeline"
            - git config --global push.default simple
            - git clone git@bitbucket.org:openid/openid.bitbucket.io.git
            - mkdir -p openid.bitbucket.io/fapi/
            - cp *.html openid.bitbucket.io/fapi/
            - cd openid.bitbucket.io/fapi
            - git add *
            - git diff-index --quiet HEAD || git commit -m "Automatic update of FAPI drafts by pipeline"
            - git push origin master
